name: tattva
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.17.0
  cloud_firestore: ^1.0.1
  cloud_functions: ^1.0.2
  cupertino_icons: ^1.0.2
  dartz: 0.10.0-nullsafety.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  flutter_bloc: ^7.0.1
  flutter_facebook_auth: ^3.1.1
  flutter_svg: ^0.21.0-nullsafety.0
  formz: 0.4.0-nullsafety.0
  freezed_annotation: ^0.14.1
  get_it: ^6.0.0
  google_sign_in: ^5.0.1
  injectable: ^1.2.0
  json_annotation: ^4.0.0
  just_audio: ^0.7.2
  provider: ^5.0.0
  auto_route: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  dio: ^4.0.0
  path_provider: ^2.0.1
  dio_cache_interceptor: ^2.0.0
  sqlite3_flutter_libs: ^0.4.1
  flutter_downloader: ^1.6.0-nullsafety.0
  permission_handler: ^6.1.1
  flutter_widget_from_html: ^0.6.0
  package_info: ^2.0.0
  firebase_dynamic_links: ^2.0.3
  share: ^2.0.1
  connectivity: ^3.0.4
  hydrated_bloc: ^7.0.1
  marquee: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  freezed: ^0.14.1
  injectable_generator: null
  auto_route_generator: ^1.0.2
  json_serializable: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - icons/

  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/AvenirNext-Regular.ttf
          weight: 400
        - asset: fonts/AvenirNext-Medium.ttf
          weight: 500
        - asset: fonts/AvenirNext-Demi.ttf
          weight: 600
